import pygame

SIZE_GAME_PLACE_X = 800
SIZE_GAME_PLACE_Y = 600

COLOR_BACKGROUND = pygame.Color(0x00, 0x00, 0x00)

CAPTION_WINDOW = "TestGame"

SIZE_PLAYER = 10
COLOR_PLAYER = [0xff, 0x00, 0x00]
SPEED_ANIMATION_PLAYER_MOVING = 5
SPEED_ANIMATION_PLAYER_ROTATION = 5

class Direction:
    DIRECTION_NONE = 0
    DIRECTION_FORWARD = 1
    DIRECTION_DOWN = 2 
    DIRECTION_LEFT = 3
    DIRECTION_RIGHT = 4

